---
users:

  'plone':
    name: 'Plone installation'
    email: 'cihan@itsnotthatkind.org'
    public_keys: ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWcrdfW6YNlAe6WK3q8u/nh/ewmuUcZKH9HK6BLbsHR"]
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
